#!/usr/bin/env bash
set -eo pipefail
echo ::group::Environment
export
echo ::endgroup::
echo "::group::Building DEDOC schema"
make -C schema
echo ::endgroup::
echo "::group::Building website"
make -C web
echo ::endgroup::
echo "::group::Collecting artifacts"
mv web/build/out gh-pages
mv schema/build gh-pages/schema
echo
echo "Final GitHub pages output:"
(cd gh-pages; find . -type f;)
echo
echo ::endgroup::
