name: Documentation
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DEDOC
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build DEDOC Schema
        run: |
          nix-shell --run .github/workflows/build-docs -p guile libxml2 libxslt rnv xmlstarlet guile

      #- name: Setup GitHub Pages
      #  uses: actions/configure-pages@v2
      #  id: pages
      #  # outputs base_url (https://foo.github.io/bar), origin, host, base_path; GITHUB_PAGES=true

      - name: Upload GitHub Pages Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: schema/build
          # path of the directory containing the static assets, default '_site/'
          # retention-days
          # name: 'github-pages' - artifact name
          #
          #
          # tar --dereference --hard-dereference --directory "$path" -cvf $RUNNER_TEMP/artifact.tar --exclude=.git --exclude=.github .
          # actions/upload-artifact@main (name=name, path=$RUNNER_TEMP/artifact.tar, retention-days=1)
          #
  publish-documentation:
    needs: build-documentation
    if: github.event_name == 'push' && github.ref_name == 'master'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: true
    environment:
      # Environment to use.
      name: github-pages
      # This just allows a link to the site to be shown on the GitHub deployments page.
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        # Deploys a GitHub Actions Artifact tar.gz as a GitHub Pages deployment.
        uses: actions/deploy-pages@v1
        id: deployment
